name: Generate ASCII Artwork

on: 
 push

jobs :
 ascii_job:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout Repo
    uses: actions/checkout@v4

  - name: list file
    run: |
        ls

  - name: Executing Shell Script
    run: |
        chmod +x ./ascii-scrip.sh
        ./ascii-scrip.sh
